export const CREATE_GAMES_REQUEST = "CREATE_GAMES_REQUEST";
export const CREATE_GAMES_SUCCESS = "CREATE_GAMES_SUCCESS";
export const CREATE_GAMES_FAIL = "CREATE_GAMES_FAIL";

export const GAME_TO_CART_ADD = "GAME_TO_CART_ADD";
export const GAME_TO_CART_REMOVE = "GAME_TO_CART_REMOVE";
export const GAME_TO_CART_CLEAR = "GAME_TO_CART_CLEAR";
export const GAME_TO_CART_EDIT = "GAME_TO_CART_EDIT";

export const GET_GAMES_LIST_REQUEST = "GET_GAMES_LIST_REQUEST";
export const GET_GAMES_LIST_SUCCESS = "GET_GAMES_LIST_SUCCESS";
export const GET_GAMES_LIST_FAIL = "GET_GAMES_LIST_FAIL";

export const GET_FREE_GAMES_LIST_REQUEST = "GET_FREE_GAMES_LIST_REQUEST";
export const GET_FREE_GAMES_LIST_SUCCESS = "GET_FREE_GAMES_LIST_SUCCESS";
export const GET_FREE_GAMES_LIST_FAIL = "GET_FREE_GAMES_LIST_FAIL";

export const GET_PREMIUM_GAMES_LIST_REQUEST = "GET_PREMIUM_GAMES_LIST_REQUEST";
export const GET_PREMIUM_GAMES_LIST_SUCCESS = "GET_PREMIUM_GAMES_LIST_SUCCESS";
export const GET_PREMIUM_GAMES_LIST_FAIL = "GET_PREMIUM_GAMES_LIST_FAIL";
