export const CREATE_GAMES_REQUEST = "CREATE_GAMES_REQUEST";
export const CREATE_GAMES_SUCCESS = "CREATE_GAMES_SUCCESS";
export const CREATE_GAMES_FAIL = "CREATE_GAMES_FAIL";

export const GAME_TO_CART_ADD = "GAME_TO_CART_ADD";
export const GAME_TO_CART_REMOVE = "GAME_TO_CART_REMOVE";
export const GAME_TO_CART_CLEAR = "GAME_TO_CART_CLEAR";
export const GAME_TO_CART_EDIT = "GAME_TO_CART_EDIT";
