export const CREATE_GAMES_REQUEST = "CREATE_GAMES_REQUEST";
export const CREATE_GAMES_SUCCESS = "CREATE_GAMES_SUCCESS";
export const CREATE_GAMES_FAIL = "CREATE_GAMES_FAIL";

export const GAME_TO_CART_ADD = "GAME_TO_CART_ADD";
export const GAME_TO_CART_REMOVE = "GAME_TO_CART_REMOVE";
export const GAME_TO_CART_CLEAR = "GAME_TO_CART_CLEAR";
export const GAME_TO_CART_EDIT = "GAME_TO_CART_EDIT";

export const GET_GAMES_LIST_REQUEST = "GET_GAMES_LIST_REQUEST";
export const GET_GAMES_LIST_SUCCESS = "GET_GAMES_LIST_SUCCESS";
export const GET_GAMES_LIST_FAIL = "GET_GAMES_LIST_FAIL";

export const GET_FREE_GAMES_LIST_REQUEST = "GET_FREE_GAMES_LIST_REQUEST";
export const GET_FREE_GAMES_LIST_SUCCESS = "GET_FREE_GAMES_LIST_SUCCESS";
export const GET_FREE_GAMES_LIST_FAIL = "GET_FREE_GAMES_LIST_FAIL";

export const GET_SHORT_FREE_GAMES_LIST_REQUEST =
  "GET_SHORT_FREE_GAMES_LIST_REQUEST";
export const GET_SHORT_FREE_GAMES_LIST_SUCCESS =
  "GET_SHORT_FREE_GAMES_LIST_SUCCESS";
export const GET_SHORT_FREE_GAMES_LIST_FAIL = "GET_SHORT_FREE_GAMES_LIST_FAIL";

export const GET_PREMIUM_GAMES_LIST_REQUEST = "GET_PREMIUM_GAMES_LIST_REQUEST";
export const GET_PREMIUM_GAMES_LIST_SUCCESS = "GET_PREMIUM_GAMES_LIST_SUCCESS";
export const GET_PREMIUM_GAMES_LIST_FAIL = "GET_PREMIUM_GAMES_LIST_FAIL";

export const UPDATE_GAMES_WASWON_REQUEST = "UPDATE_GAMES_WASWON_REQUEST";
export const UPDATE_GAMES_WASWON_SUCCESS = "UPDATE_GAMES_WASWON_SUCCESS";
export const UPDATE_GAMES_WASWON_FAIL = "UPDATE_GAMES_WASWON_FAIL";

export const DELETE_GAME_REQUEST = "DELETE_GAME_REQUEST";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAIL = "DELETE_GAME_FAIL";
