export const GET_PAYSTACK_CONFIG_REQUEST = "GET_PAYSTACK_CONFIG_REQUEST";
export const GET_PAYSTACK_CONFIG_SUCCESS = "GET_PAYSTACK_CONFIG_SUCCESS";
export const GET_PAYSTACK_CONFIG_FAIL = "GET_PAYSTACK_CONFIG_FAIL";
