export const GET_PAYSTACK_CONFIG_REQUEST = "GET_PAYSTACK_CONFIG_REQUEST";
export const GET_PAYSTACK_CONFIG_SUCCESS = "GET_PAYSTACK_CONFIG_SUCCESS";
export const GET_PAYSTACK_CONFIG_FAIL = "GET_PAYSTACK_CONFIG_FAIL";

export const CONFIRM_PAYSTACK_PAYMENT_REQUEST =
  "CONFIRM_PAYSTACK_PAYMENT_REQUEST";
export const CONFIRM_PAYSTACK_PAYMENT_SUCCESS =
  "CONFIRM_PAYSTACK_PAYMENT_SUCCESS";
export const CONFIRM_PAYSTACK_PAYMENT_FAIL = "CONFIRM_PAYSTACK_PAYMENT_FAIL";

export const GET_ACTIVE_SUBSCRIPTIONS_REQUEST =
  "GET_ACTIVE_SUBSCRIPTIONS_REQUEST";
export const GET_ACTIVE_SUBSCRIPTIONS_SUCCESS =
  "GET_ACTIVE_SUBSCRIPTIONS_SUCCESS";
export const GET_ACTIVE_SUBSCRIPTIONS_FAIL = "GET_ACTIVE_SUBSCRIPTIONS_FAIL";
