export const SUPER_GET_REGULAR_USERS_REQUEST =
  "SUPER_GET_REGULAR_USERS_REQUEST";
export const SUPER_GET_REGULAR_USERS_SUCCESS =
  "SUPER_GET_REGULAR_USERS_SUCCESS";
export const SUPER_GET_REGULAR_USERS_FAIL = "SUPER_GET_REGULAR_USERS_FAIL";
