export const SUPER_GET_REGULAR_USERS_REQUEST =
  "SUPER_GET_REGULAR_USERS_REQUEST";
export const SUPER_GET_REGULAR_USERS_SUCCESS =
  "SUPER_GET_REGULAR_USERS_SUCCESS";
export const SUPER_GET_REGULAR_USERS_FAIL = "SUPER_GET_REGULAR_USERS_FAIL";

export const SUPER_MAKE_USER_ADMIN_REQUEST = "SUPER_MAKE_USER_ADMIN_REQUEST";
export const SUPER_MAKE_USER_ADMIN_SUCCESS = "SUPER_MAKE_USER_ADMIN_SUCCESS";
export const SUPER_MAKE_USER_ADMIN_FAIL = "SUPER_MAKE_USER_ADMIN_FAIL";
