export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_VERIFICATION_REQUEST = "USER_VERIFICATION_REQUEST";
export const USER_VERIFICATION_SUCCESS = "USER_VERIFICATION_SUCCESS";
export const USER_VERIFICATION_FAIL = "USER_VERIFICATION_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const CHECK_USER_TOKEN_REQUEST = "CHECK_USER_TOKEN_REQUEST";
export const CHECK_USER_TOKEN_SUCCESS = "CHECK_USER_TOKEN_SUCCESS";
export const CHECK_USER_TOKEN_FAIL = "CHECK_USER_TOKEN_FAIL";
