export const games = [
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Man U - Chelsea",
    clubsFull: "Manchester United - Chealsea",
    win: "1x",
    ov: "Ov 1.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "RMadrid - Barca",
    clubsFull: "Real Madrid - Barcalona",
    win: "1x",
    ov: "Ov 1.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: false,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Liverpool - Arsenal",
    clubsFull: "LIverpool FC- Chealsea FC",
    win: "x",
    ov: "Ov 1.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Genk - Gent",
    clubsFull: "Genk FC - Gent FC",
    win: "x2",
    ov: "Ov 2.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Genk - Gent",
    clubsFull: "Genk FC - Gent FC",
    win: "x2",
    ov: "Ov 2.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Genk - Gent",
    clubsFull: "Genk FC - Gent FC",
    win: "x2",
    ov: "Ov 2.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Genk - Gent",
    clubsFull: "Genk FC - Gent FC",
    win: "x2",
    ov: "Ov 2.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
  {
    league: "EPL",
    leagueFull: "English Premier League",
    country: "ENG",
    countryFull: "England",
    clubs: "Genk - Gent",
    clubsFull: "Genk FC - Gent FC",
    win: "x2",
    ov: "Ov 2.5",
    gg: "GG",
    corner: "Ov 7.5",
    wasWon: true,
    matchTime: "8:50am 7/10/2021",
  },
]
